---
# Sets the FQDN of a machine

- name: set FQDN for IPv4 in hosts file
  lineinfile:
      dest=/etc/hosts
    regexp="^127.0.0.1"
      line="127.0.0.1{{ '\t' }}{{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %}{{ '\t' }}{{ inventory_hostname_short }}{% endif %}{{ '\t' }}localhost"
     state=present

- name: set FQDN for IPv6 in hosts file
  lineinfile:
      dest=/etc/hosts
    regexp="^::1"
      line="::1{{ '\t\t' }}{{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %}{{ '\t' }}{{ inventory_hostname_short }}{% endif %}{{ '\t' }}localhost ip6-localhost ip6-loopback"
     state=present
