---
# Sets the hostname of a machine

- name: set hostname temporarily
  hostname: name="{{ inventory_hostname_short }}"

- name: set hostname permanently
  copy:
    content="{{ inventory_hostname_short }}{{'\n'}}"
       dest=/etc/hostname
      owner=root
      group=root
       mode=0644
